############################################################################
# My AI Tool - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = my_ai_tool
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_CONTEST2026_307_MY_AI_TOOL)

MAINSRC = my_ai_tool_main.c

include $(APPDIR)/Application.mk
